parameters:

    #
    # Entity classes
    #
    elcodi.admin.product.form_type.product.class: Elcodi\AdminProductBundle\Form\Type\ProductType
    elcodi.admin.product.form_type.variant.class: Elcodi\AdminProductBundle\Form\Type\VariantType
    elcodi.admin.product.form_type.category.class: Elcodi\AdminProductBundle\Form\Type\CategoryType
    elcodi.admin.product.form_type.manufacturer.class: Elcodi\AdminProductBundle\Form\Type\ManufacturerType
