services:

    #
    # Form Types
    #
    elcodi_admin.form_type.attribute:
        class: Elcodi\Admin\AttributeBundle\Form\Type\AttributeType
        calls:
            - [setFactory, ["@elcodi.factory.attribute"]]
        tags:
            - { name: form.type, alias: elcodi_admin_attribute_form_type_attribute }
