imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @ElcodiBambooBundle/Resources/config/translations.yml }
    - { resource: @ElcodiBambooBundle/Resources/config/mapping.yml }
    - { resource: @ElcodiBambooBundle/Resources/config/filesystem.yml }
    - { resource: @ElcodiBambooBundle/Resources/config/configuration.yml }
    - { resource: @ElcodiBambooBundle/Resources/config/cache.yml }
    - { resource: @ElcodiBambooBundle/Resources/config/page.yml }
    - { resource: @ElcodiBambooBundle/Resources/config/metrics.yml }
    - { resource: config_local.yml, ignore_errors: true }

framework:
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    translator:
        fallback: "%locale%"

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: false

    globals:
        elcodi_context: []
        currency_wrapper: @elcodi.wrapper.currency
        store_tracker: @elcodi.store_tracker

# Doctrine Configuration
doctrine:
    dbal:
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                connection: default
                auto_mapping: false

# Assetic Configuration
assetic:
    bundles:
        - AdminCoreBundle
        - StoreCoreBundle
        - StoreTemplateBundle
    debug:          "%kernel.debug%"
    use_controller: false
    filters:
        cssrewrite: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

sensio_framework_extra:
    request:
        converters: false

controller_extra:
    factory:
        default_method: create
        default_static: false

free_payment:
    payment_success:
        route: store_order_thanks
        order_append: true
        order_append_field: id

paypal_web_checkout:
    business: %paypal_web_checkout_recipient%
    payment_process:
        route: store_payment_process
    payment_success:
        route: store_order_thanks
        order_append: true
        order_append_field: id
    payment_cancel:
        route: store_homepage
        order_append: false
    payment_fail:
        route: store_checkout_payment_fail
        order_append: true
        order_append_field: id

paymill:
    public_key: %paymill_public_key%
    private_key: %paymill_private_key%
    payment_success:
        route: store_order_thanks
        order_append: true
        order_append_field: id
    payment_fail:
        route: store_checkout_payment_fail
        order_append: true
    form:
        submit_label: Continue
        submit_css_class: "btn btn-primary"

hwi_oauth:
    firewall_name: %bamboo_store_firewall%
    resource_owners:
        github:
            type: github
            client_id: %bamboo_social_github_client_id%
            client_secret: %bamboo_social_github_client_secret%
        paypal:
            type: paypal
            client_id: %bamboo_social_paypal_client_id%
            client_secret: %bamboo_social_paypal_client_secret%
            options:
                sandbox: %bamboo_social_paypal_client_is_sandbox%

#
# Elcodi related configuration
#

elcodi_bamboo:
    store_tracker: 7s89da7s8d9a

elcodi_media:
    images:
        resize:
            converter_bin_path: %imagick_convert_bin_path%

#
# Location manager. If your location is going to be managed through another
# entity manager, be sure to change this value with the name of it. By default,
# the "default" entity manager will be used
#
elcodi_geo:
    mapping:
        location:
            manager: default

