imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @ElcodiBambooBundle/Resources/config/translations.yml }
    - { resource: @ElcodiBambooBundle/Resources/config/mapping.yml }
    - { resource: @ElcodiBambooBundle/Resources/config/filesystem.yml }
    - { resource: @ElcodiBambooBundle/Resources/config/configuration.yml }
    - { resource: @ElcodiBambooBundle/Resources/config/cache.yml }
    - { resource: @ElcodiBambooBundle/Resources/config/page.yml }
    - { resource: @ElcodiBambooBundle/Resources/config/metrics.yml }

framework:
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: false

    globals:
        currency_wrapper: @elcodi.currency_wrapper
        store_tracker: %elcodi.core.bamboo.store_tracker%

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: false

# Assetic Configuration
assetic:
    bundles:
        - AdminCoreBundle
        - StoreCoreBundle
    debug:          "%kernel.debug%"
    use_controller: false
    filters:
        cssrewrite: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

sensio_framework_extra:
    request:
        converters: false

controller_extra:
    factory:
        default_method: create
        default_static: false

free_payment:
    payment_success:
        route: store_order_thanks
        order_append: true
        order_append_field: id

paypal_web_checkout:
    business: %paypal_web_checkout_recipient%
    payment_process:
        route: store_payment_process
    payment_success:
        route: store_order_thanks
        order_append: true
        order_append_field: id
    payment_cancel:
        route: store_homepage
        order_append: false
    payment_fail:
        route: store_checkout_payment_fail
        order_append: true
        order_append_field: id

hwi_oauth:
    firewall_name: customer_secured_area
    resource_owners:
        github:
            type: github
            client_id: %bamboo_social_github_client_id%
            client_secret: %bamboo_social_github_client_secret%
        paypal:
            type: paypal
            client_id: %bamboo_social_paypal_client_id%
            client_secret: %bamboo_social_paypal_client_secret%
            options:
                sandbox: %bamboo_social_paypal_client_is_sandbox%

elcodi_bamboo:
    store_tracker: 7s89da7s8d9a
