security:
    firewalls:
        dev_area:
            pattern:  ^/_(?:profiler|wdt|error)/
            security: false

        public_area:
            pattern:  ^/(?:css|images|js)/
            security: false

        admin_login_area:
            pattern: ^/%bamboo_admin_prefix%/login$
            anonymous: ~

        admin_password_area:
            pattern: ^/%bamboo_admin_prefix%/password/
            anonymous: ~

        admin_area:
            provider: adminuser
            pattern: ^/%bamboo_admin_prefix%/
            simple-preauth:
                authenticator: admin.user.security.one_time_login_authenticator
            form_login:
                login_path: admin_login
                check_path: admin_login_check
                username_parameter: elcodi_admin_user_form_type_login[email]
                password_parameter: elcodi_admin_user_form_type_login[password]
                default_target_path: admin_homepage
            logout:
                path:   admin_logout
                target: admin_homepage
                invalidate_session: false

        store_area:
            provider: customer
            anonymous: true
            form_login:
                login_path: store_login
                check_path: store_login_check
                username_parameter: store_user_form_type_login[email]
                password_parameter: store_user_form_type_login[password]
            logout:
                path:   store_logout
                target: store_homepage
                invalidate_session: false
            oauth:
                login_path: /login
                use_forward: false
                failure_path: /login
                oauth_user_provider:
                    service: store.connect.service.oauth_provider
                resource_owners:
                    github: /login/check-github
                    paypal: /login/check-paypal
