#
# Admin routes
#
admin_core:
    resource: "@AdminCoreBundle/Resources/config/routing.yml"
    prefix: /%bamboo_admin_prefix%

admin_user:
    resource: "@AdminUserBundle/Resources/config/routing.yml"
    prefix: /%bamboo_admin_prefix%

admin_cart:
    resource: "@AdminCartBundle/Resources/config/routing.yml"
    prefix: /%bamboo_admin_prefix%

admin_banner:
    resource: "@AdminBannerBundle/Resources/config/routing.yml"
    prefix: /%bamboo_admin_prefix%

admin_coupon:
    resource: "@AdminCouponBundle/Resources/config/routing.yml"
    prefix: /%bamboo_admin_prefix%

admin_currency:
    resource: "@AdminCurrencyBundle/Resources/config/routing.yml"
    prefix: /%bamboo_admin_prefix%

admin_attribute:
    resource: "@AdminAttributeBundle/Resources/config/routing.yml"
    prefix: /%bamboo_admin_prefix%

admin_product:
    resource: "@AdminProductBundle/Resources/config/routing.yml"
    prefix: /%bamboo_admin_prefix%

admin_language:
    resource: "@AdminLanguageBundle/Resources/config/routing.yml"
    prefix: /%bamboo_admin_prefix%

admin_media:
    resource: "@AdminMediaBundle/Resources/config/routing.yml"
    prefix: /%bamboo_admin_prefix%

admin_newsletter:
    resource: "@AdminNewsletterBundle/Resources/config/routing.yml"
    prefix: /%bamboo_admin_prefix%

admin_page:
    resource: "@AdminPageBundle/Resources/config/routing.yml"
    prefix: /%bamboo_admin_prefix%

admin_configuration:
    resource: "@AdminConfigurationBundle/Resources/config/routing.yml"
    prefix: /%bamboo_admin_prefix%

admin_templates:
    resource: "@AdminTemplateBundle/Resources/config/routing.yml"
    prefix: /%bamboo_admin_prefix%

admin_plugins:
    resource: "@AdminPluginBundle/Resources/config/routing.yml"
    prefix: /%bamboo_admin_prefix%

admin_metric:
    resource: "@AdminMetricBundle/Resources/config/routing.yml"
    prefix: /%bamboo_admin_prefix%

admin_login_check:
    path:  /%bamboo_admin_prefix%/login_check

admin_logout:
    path: /%bamboo_admin_prefix%/logout

#
# Store routes
#
store_core:
    resource: "@StoreCoreBundle/Resources/config/routing.yml"

store_product:
    resource: "@StoreProductBundle/Resources/config/routing.yml"

store_user:
    resource: "@StoreUserBundle/Resources/config/routing.yml"

store_cart:
    resource: "@StoreCartBundle/Resources/config/routing.yml"

store_cart_coupon:
    resource: "@StoreCartCouponBundle/Resources/config/routing.yml"

store_currency:
    resource: "@StoreCurrencyBundle/Resources/config/routing.yml"

payment:
    resource: "@PaymentBridgeBundle/Resources/config/routing.yml"

store_login_check:
    path:  /login_check

store_logout:
    path: /logout

core_media_bundle:
    resource: "@ElcodiMediaBundle/Resources/config/routing.yml"

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

github_login:
    pattern: /login/check-github

paypal_login:
    pattern: /login/check-paypal

#
# Plugins routes
#
elcodi_plugin_pinterest:
    resource: "@ElcodiPinterestBundle/Resources/config/routing.yml"
    prefix: /%bamboo_admin_prefix%/plugin

elcodi_plugin_google_analytics:
    resource: "@ElcodiGoogleAnalyticsBundle/Resources/config/routing.yml"
    prefix: /%bamboo_admin_prefix%/plugin

elcodi_plugin_product_csv:
    resource: "@ElcodiProductCsvBundle/Resources/config/routing.yml"
    prefix: /%bamboo_admin_prefix%/plugin

#
# Elcodi routes
#
elcodi_metric:
    resource: "@ElcodiMetricBundle/Resources/config/routing.yml"
    prefix: /

elcodi_comment:
    resource: "@ElcodiCommentBundle/Resources/config/routing.yml"
    prefix: /api

elcodi_page:
    resource: "@ElcodiPageBundle/Resources/config/routing.yml"
    prefix: /