parameters:

    #
    # Entity classes
    #
    elcodi.admin.currency.form_type.currency.class: Elcodi\Admin\CurrencyBundle\Form\Type\CurrencyType
    elcodi.admin.currency.form_type.money.class: Elcodi\Admin\CurrencyBundle\Form\Type\MoneyType
