parameters:

    #
    # Repositories
    #
    store.connect.repository.authorization.class: Doctrine\ORM\EntityRepository

    #
    # Services
    #
    store.connect.service.oauth_provider.class: Elcodi\Store\StoreConnectBundle\Services\OAuthUserProvider
